### ISSUE TITLE
File name too long issue while building openconfig-network-instance.yang

### ISSUE THREAD

**Issue by venkatmahalingam** [project-arlo/sonic-mgmt-framework#140]
I'm getting the following build error (File name too long) while compiling the openconfig-network-instance.yang (in yang folder and various dependent YANGs in common folder), can you please take a look?
```
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /sonic/src/sonic-mgmt-framework/models/../build/rest_server/codegen/openconfig-network-instance/go/model_get_openconfig_network_instance_network_instances_network_instance_protocols_protocol_isis_levels_level_link_state_database_lsp_tlvs_tlv_extended_is_reachability_neighbors_neighbor_instances_instance_subtlvs_subtlv_adjacency_sids_adjacency_sid_state.go
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'get_openconfig_network_instance_network_instances_network_instance_protocols_protocol_isis_levels_level_link_state_database_lsp_tlvs_tlv_extended_is_reachability_neighbors_neighbor_instances_instance_subtlvs_subtlv_adjacency_sids_adjacency_sid_state'
       at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:425)
       at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:751)
       at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
       at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.io.FileNotFoundException: /sonic/src/sonic-mgmt-framework/models/../build/rest_server/codegen/openconfig-network-instance/go/model_get_openconfig_network_instance_network_instances_network_instance_protocols_protocol_isis_levels_level_link_state_database_lsp_tlvs_tlv_extended_is_reachability_neighbors_neighbor_instances_instance_subtlvs_subtlv_adjacency_sids_adjacency_sid_state.go (File name too long)
       at java.io.FileOutputStream.open0(Native Method)
       at java.io.FileOutputStream.open(FileOutputStream.java:270)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
       at io.swagger.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:32)
       at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:780)
       at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:412)
       ... 3 more
Makefile:90: recipe for target '../build/rest_server/codegen/openconfig-network-instance/.yangapi_done' failed
make[4]: *** [../build/rest_server/codegen/openconfig-network-instance/.yangapi_done] Error 1
make[4]: Leaving directory '/sonic/src/sonic-mgmt-framework/models'
Makefile:57: recipe for target '/sonic/src/sonic-mgmt-framework/build/rest_server/main' failed
make[3]: *** [/sonic/src/sonic-mgmt-framework/build/rest_server/main] Error 2
make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/rest'
Makefile:83: recipe for target 'rest-server' failed
make[2]: *** [rest-server] Error 2
make[2]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dh_auto_build: make -j1 returned exit code 2
debian/rules:3: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
[  FAIL LOG END  ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
slave.mk:329: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
make: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 1
Makefile.work:191: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
make[1]: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 2
make[1]: Leaving directory '/neteng/vmahalingam/NGOS/arlo/sonic-buildimage'
Makefile:6: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
make: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 2
```

**Comment by jeffyin-dell** [comment]
@faraazbrcm any update? Did Venkat assign it to the right person?

**Comment by venkatmahalingam** [comment]
@jeff-yin I got the private changes from @faraazbrcm, the build is fine now.

**Comment by faraazbrcm** [comment]
Fixed in the latest version of master

**Comment by linemma** [comment]
I'm getting this build error, too. Could you please help me fix this issue? Thanks.

**Comment by EmmaLin11** [comment]
I'm getting this build error, too. Could you please help me fix this error? 
Which file should be updated so that the error will not occur?
Thanks.

**Comment by faraazbrcm** [comment]
@linemma you need to update sonic-buildimage/src/sonic-mgmt-framework/tools/pyang/pyang_plugins/openapi.py file
If the LATEST in the master is not fixing it, please use the attached file

[openapi.py.zip](https://github.com/project-arlo/sonic-mgmt-framework/files/4580104/openapi.py.zip)
unzip the content and use it.

Also, it requires a python module mmh3 (https://pypi.org/project/mmh3/) installed in the build system
sonic-buildimage/sonic-slave-stretch/Dockerfile.j2
sonic-buildimage/sonic-slave/Dockerfile.j2

**Comment by EmmaLin11** [comment]
@faraazbrcm, thank you! After I use the new openapi.py, it can build success.
