### ISSUE TITLE
Getting single interface does not work in gNMI, rest or CLI

### ISSUE THREAD

**Issue by seiferteric** [project-arlo/sonic-mgmt-framework#186]
Getting a single interface results in a failure. Getting all interfaces works as expected.

Syslog:
```
Oct 18 01:07:41.809784 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: No managment ports found in b'MGMT_PORT|'
Oct 18 01:07:42.170872 sonic ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py", line 83, in reinit_data#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py", line 96, in update_data#012    self.update_stats()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py", line 127, in update_stats#012    queue_type = self.queue_type_map.get(queue_sai_oid)#012AttributeError: 'NoneType' object has no attribute 'get'
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274580      17 router.go:122] [REST-9] Recevied GetOpenconfigInterfacesInterfacesInterface request from 127.0.0.1:40634
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274616      17 handler.go:47] [REST-9] GET /restconf/data/openconfig-interfaces:interfaces/interface=Ethernet0; content-len=0
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274624      17 handler.go:92] [REST-9] No body
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274635      17 handler.go:55] [REST-9] Translated path = /openconfig-interfaces:interfaces/interface[name=Ethernet0]
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274641      17 translib.go:406] Received Get request for path = /openconfig-interfaces:interfaces/interface[name=Ethernet0]
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274648      17 app_interface.go:130] getAppModule called for path =/openconfig-interfaces:interfaces/interface[name=Ethernet0]
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274653      17 app_interface.go:137] found the entry in the map for path =/openconfig-interfaces:interfaces
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274661      17 app_interface.go:165] cast to appInterface worked&{<nil> [] <nil> <nil> <nil> [] <nil> <nil> 0 { 0} {<nil> <nil> <nil> {0 {map[]}} map[] <nil> <nil> <nil> map[] []} {<nil> <nil> <nil> <nil> map[]} map[]}
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274859      17 intf_app.go:140] initialize:if:path =/openconfig-interfaces:interfaces/interface[name=Ethernet0]
Oct 18 01:07:42.275474 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274924      17 db.go:324] NewDB: Init indication not requested
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274947      17 intf_app.go:263] translateGet:intf:path =&{/openconfig-interfaces:interfaces/interface[name=Ethernet0] /openconfig-interfaces:interfaces/interface{} map[name:Ethernet0]}
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274960      17 intf_app.go:373] Received GET for path /openconfig-interfaces:interfaces/interface[name=Ethernet0]; template: /openconfig-interfaces:interfaces/interface{} vars=map[name:Ethernet0]
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274985      17 intf_app.go:378] URI Path = /openconfig-interfaces:interfaces/interface
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274991      17 intf_cmn.go:903] Received GET for path /openconfig-interfaces:interfaces/interface[name=Ethernet0]; template: /openconfig-interfaces:interfaces/interface{} vars=map[name:Ethernet0]
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.274999      17 intf_cmn.go:908] Interface Name = Ethernet0
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.275004      17 intf_cmn.go:477] Updating Interface info from APP-DB to Internal DS for Interface name : Ethernet0
Oct 18 01:07:42.275807 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.275297      17 intf_cmn.go:486] Interface Info populated for ifName : Ethernet0
Oct 18 01:07:42.275857 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.275505      17 intf_cmn.go:440] Found 0 vlan-member-table keys
Oct 18 01:07:42.275857 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.275514      17 intf_cmn.go:467] Updated the vlan-member-table ds for Interface: Ethernet0
Oct 18 01:07:42.276748 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.276357      17 intf_cmn.go:409] OID : oid:0x1000000000002 received for Interface : Ethernet0
Oct 18 01:07:42.276960 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.276516      17 intf_cmn.go:510] Updating Interface IP Info from APP-DB to Internal DS for Interface Name : Ethernet0
Oct 18 01:07:42.280171 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.279911      17 intf_utils.go:289] Found 33 INTF table keys
Oct 18 01:07:42.283119 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.282853      17 intf_cmn.go:130] /openconfig-interfaces:interfaces/interface - Not an interface state attribute
Oct 18 01:07:42.283119 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.282869      17 intf_cmn.go:266] /openconfig-interfaces:interfaces/interface - Not an interface state counter attribute
Oct 18 01:07:42.283338 sonic INFO mgmt-framework#supervisord: rest-server E1018 01:07:42.282921      17 handler.go:59] [REST-9] Translib error *errors.errorString - Requested get type not supported!
Oct 18 01:07:42.283338 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.282949      17 handler.go:72] [REST-9] Sending response 500, type=application/yang-data+json, data={"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"operation-failed"}]}}
Oct 18 01:07:42.283338 sonic INFO mgmt-framework#supervisord: rest-server I1018 01:07:42.282965      17 router.go:128] [REST-9] GetOpenconfigInterfacesInterfacesInterface took 8.359998ms
```

gNMI Command:
```./gnmi_get -xpath /openconfig-interfaces:interfaces/interface[name=Ethernet0] -insecure -target_addr localhost:8080
F1018 01:01:38.032543    8690 gnmi_get.go:137] Get failed: rpc error: code = NotFound desc = GET failed for this message

```

Rest:
```
curl -k https://localhost/restconf/data/openconfig-interfaces:interfaces/interface=Ethernet0
{"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"operation-failed"}]}}
```

CLI:
```
sonic# show interface Ethernet 0
%Error: Transaction Failure
```

**Comment by jeffyin-dell** [comment]
@s-mari @justinejose91 -- was this broken and then fixed recently?

**Comment by justinejose91** [comment]
@jeff-yin I will have a look at this issue tomorrow Jeff

**Comment by justinejose91** [comment]
Pull-request raised, tested myself and tested with @seiferteric setup.

**Comment by jeffyin-dell** [comment]
@seiferteric -- please verify in the latest `master` code and close the bug if resolved.

**Comment by seiferteric** [comment]
Verified working now.
