### ISSUE TITLE
Traceback error returned when "show mac address-table" and its relevant commands are given

### ISSUE THREAD

**Issue by KarthikKumarGoudBattula** [project-arlo/sonic-mgmt-framework#251]
sonic#
sonic#
sonic#
sonic# show mac address-table
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-mac.py", line 24, in <module>
    import openconfig_network_instance_client
ImportError: No module named openconfig_network_instance_client

sonic# show mac address-table interface Ethernet 0
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-mac.py", line 24, in <module>
    import openconfig_network_instance_client
ImportError: No module named openconfig_network_instance_client

sonic# show mac address-table static
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-mac.py", line 24, in <module>
    import openconfig_network_instance_client
ImportError: No module named openconfig_network_instance_client

sonic# show mac address-table dynamic
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-mac.py", line 24, in <module>
    import openconfig_network_instance_client
ImportError: No module named openconfig_network_instance_client

sonic# show mac address-table static interface Ethernet 0
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-mac.py", line 24, in <module>
    import openconfig_network_instance_client
ImportError: No module named openconfig_network_instance_client
sonic#

**Comment by bhavini-gada** [comment]
@KarthikKumarGoudBattula - We need to make some updates after the generic REST client changes.  @sachinholla -  FYI

**Comment by ViramShah91** [comment]
I have raised pull-request for the fix.

https://github.com/project-arlo/sonic-mgmt-framework/pull/265
