### ISSUE TITLE
rest-server panic at CVL init phase when the prefix of a leafref has a "-" (ex: mgmt-vrf)

### ISSUE THREAD

**Issue by rvasanthm** [project-arlo/sonic-mgmt-framework#281]
```
Nov 15 22:05:35.751201 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse: I1115 22:05:35.750277     271 util.go:154] Parsing schema file /usr/sbin/schema/sonic-wred-profile.yin ...
Nov 15 22:05:35.751201 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse: I1115 22:05:35.750380     271 util.go:154] Parsing schema file /usr/sbin/schema/sonic-wred-profile.yin ...
Nov 15 22:05:35.814566 sonic INFO mgmt-framework#supervisord: rest-server panic: runtime error: invalid memory address or nil pointer dereference
Nov 15 22:05:35.815155 sonic INFO mgmt-framework#supervisord: rest-server [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9a0269]
Nov 15 22:05:35.815767 sonic INFO mgmt-framework#supervisord: rest-server
Nov 15 22:05:35.816247 sonic INFO mgmt-framework#supervisord: rest-server goroutine 1 [running]:
Nov 15 22:05:35.816690 sonic INFO mgmt-framework#supervisord: rest-server cvl.buildRefTableInfo()
Nov 15 22:05:35.817109 sonic INFO mgmt-framework#supervisord: rest-server #011/sonic/src/sonic-mgmt-framework/src/cvl/cvl.go:438
Nov 15 22:05:35.817751 sonic INFO mgmt-framework#supervisord: rest-server  +0x379
Nov 15 22:05:35.817981 sonic INFO mgmt-framework#supervisord: rest-server cvl.init.0()
Nov 15 22:05:35.818189 sonic INFO mgmt-framework#supervisord: rest-server #011/sonic/src/sonic-mgmt-framework/src/cvl/cvl.go:212 +0x688
Nov 15 22:05:40.016097 sonic INFO mgmt-framework#supervisord: rest-server Generating temporary TLS server certificate ...
Nov 15 22:05:41.711723 sonic INFO mgmt-framework#supervisord 2019-11-15 22:05:35,822 INFO exited: rest-server (exit status 2; expected)
Nov 15 22:05:41.712668 sonic INFO mgmt-framework#supervisord 2019-11-15 22:05:36,829 INFO spawned: 'rest-server' with pid 292
Nov 15 22:05:41.712945 sonic INFO mgmt-framework#supervisord 2019-11-15 22:05:37,838 INFO success: rest-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Nov 15 22:05:43.030690 sonic INFO mgmt-framework#supervisord: rest-server 2019/11/15 22:05:43 wrote cert.pem
Nov 15 22:05:43.030690 sonic INFO mgmt-framework#supervisord: rest-server 2019/11/15 22:05:43 wrote key.pem
Nov 15 22:05:43.047441 sonic INFO mgmt-framework#supervisord: rest-server REST_SERVER_ARGS = -ui /rest_ui -logtostderr -cert /tmp/cert.pem -key /tmp/key.pem
Nov 15 22:05:43.076551 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse: I1115 22:05:43.073772     292 util.go:163] Current Values of CVL Configuration File map[STDERRTHRESHOLD:INFO SKIP_SEMANTIC_VALIDATION:false TRACE_YPARSER:true TRACE_UPDATE:true TRACE_SYNTAX:true TRACE_DELETE:true TRACE_SEMANTIC:true VERBOSITY:8 TRACE_CREATE:true LOGTOSTDERR:false __comment2__:Display log upto INFO level __comment1__:Set LOGTOSTDER to 'true' to log on standard error __comment3__:Display log upto INFO level 8 SKIP_VALIDATION:false TRACE_CACHE:true TRACE_LIBYANG:true TRACE_ONERROR:true]
Nov 15 22:05:43.077354 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse: I1115 22:05:43.074556     292 util.go:163] Current Values of CVL Configuration File map[TRACE_DELETE:true TRACE_SEMANTIC:true VERBOSITY:8 TRACE_CREATE:true LOGTOSTDERR:false __comment2__:Display log upto INFO level __comment1__:Set LOGTOSTDER to 'true' to log on standard error __comment3__:Display log upto INFO level 8 SKIP_VALIDATION:false TRACE_CACHE:true TRACE_LIBYANG:true TRACE_ONERROR:true STDERRTHRESHOLD:INFO SKIP_SEMANTIC_VALIDATION:false TRACE_YPARSER:true TRACE_UPDATE:true TRACE_SYNTAX:true]
Nov 15 22:05:43.177418 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse:
Nov 15 22:05:43.181881 sonic INFO mgmt-framework#supervisord: rest-server I1115 22:05:43.175409     292 util.go:154] Parsing schema file /usr/sbin/schema/sonic-acl-deviation.yin ...
Nov 15 22:05:43.186418 sonic INFO mgmt-framework#supervisord: rest-server ERROR: logging before flag.Parse: I1115 22:05:43.182253     292 util.go:154] Parsing schema file /usr/sbin/schema/sonic-acl-deviation.yin ...
```

**Comment by dutta-partha** [comment]
Fix is available in project-arlo:broadcom_sonic_share. Please check and update.
