### ISSUE TITLE
Occasional crashes when getting acl-set

### ISSUE THREAD

**Issue by seiferteric** [project-arlo/sonic-mgmt-framework#58]
Sometimes when doing a gnmi get on an acl-set, I am getting a panic that seems to originate in the acl_app.go. I am running this command: `./gnmi_get -xpath /openconfig-acl:acl/acl-sets/acl-set[name=MyACL1][type=ACL_IPV4] -target_addr 127.0.0.1:8080 -insecure`

This also affects gnmi subscribe since it is periodically doing Gets and if one crashes, it kills the subscription.
```
pathList[0]: name:"openconfig-acl:acl" 
pathList[1]: name:"acl-sets" 
pathList[2]: name:"acl-set" key:<key:"name" value:"MyACL1" > key:<key:"type" value:"ACL_IPV4" > 
Target yang name: acl-set  OC Field name: AclSet
I0802 16:48:08.214326   26519 translib.go:399] Received Get request for path = /openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL1]
I0802 16:48:08.214497   26519 app_interface.go:116] getAppModule called for path =/openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL1]
I0802 16:48:08.214566   26519 app_interface.go:123] found the entry in the map for path =/openconfig-acl:acl
I0802 16:48:08.214643   26519 app_interface.go:154] cast to appInterface worked&{<nil> <nil> <nil> <nil> <nil> map[] map[] false false false}
I0802 16:48:08.214842   26519 acl_app.go:105] initialize:acl:path =/openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL1]
I0802 16:48:08.215035   26519 db.go:307] NewDB: Init indication not requested
I0802 16:48:08.215113   26519 acl_app.go:162] translateGet:acl:path =/openconfig-acl:acl/acl-sets/acl-set{type}{name}
I0802 16:48:08.215219   26519 acl_app.go:305] processCommon--Path Received: /openconfig-acl:acl/acl-sets/acl-set{type}{name}
I0802 16:48:08.215326   26519 acl_app.go:308] processCommon: Target object is a <ptr> of Type: OpenconfigAcl_Acl_AclSets_AclSet
Error handling:  duplicate key {MyACL1 1} for list AclSet
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 661 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.12/src/reflect/value.go:1813 +0x169
github.com/openconfig/ygot/ygot.BuildEmptyTree(0xd8d100, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/github.com/openconfig/ygot/ygot/struct_validation_map.go:140 +0xd7
translib.(*AclApp).convertInternalToOCAcl(0xc00007ac80, 0x0, 0x0, 0xc0000b2170, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:614 +0x37a
translib.(*AclApp).processCommonToplevelPath(0xc00007ac80, 0xc00095a480, 0xc0002e7980, 0x1, 0x0, 0x0, 0x2)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:502 +0x16a
translib.(*AclApp).processCommon(0xc00007ac80, 0xc00095a480, 0x1, 0x2, 0x2)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:420 +0x1b5a
translib.(*AclApp).processGet(0xc00007ac80, 0xc00095a300, 0xc00095a360, 0xc00095a3c0, 0xc00095a420, 0xc00095a480, 0x0, 0xc00095a4e0, 0x0, 0x0, ...)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:275 +0x45
translib.Get(0xc000508c80, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/translib.go:431 +0x2ea
transl_utils.TranslProcessGet(0xc000508c80, 0x40, 0x0, 0x0, 0x0, 0xb581c0)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/transl_utils/transl_utils.go:83 +0x4d
sonic_data_client.(*TranslClient).Get(0xc0005ae640, 0x0, 0x1, 0xc0000b2130, 0xda2720, 0xc0005ae640, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/sonic_data_client/transl_data_client.go:64 +0x123
gnmi_server.(*Server).Get(0xc0002e40c0, 0xd9c080, 0xc00068aa20, 0xc0006ac000, 0xc0002e40c0, 0xc00068aa20, 0xc0006b5ba8)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/gnmi_server/server.go:181 +0x417
github.com/openconfig/gnmi/proto/gnmi._GNMI_Get_Handler(0xc04340, 0xc0002e40c0, 0xd9c080, 0xc00068aa20, 0xc0005ae5f0, 0x0, 0xd9c080, 0xc00068aa20, 0xc0004dbec0, 0x55)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/github.com/openconfig/gnmi/proto/gnmi/gnmi.pb.go:2442 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d0000, 0xda4760, 0xc000646480, 0xc00079a100, 0xc0002e4210, 0x1534a98, 0x0, 0x0, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:989 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc0000d0000, 0xda4760, 0xc000646480, 0xc00079a100, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:1269 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00058d160, 0xc0000d0000, 0xda4760, 0xc000646480, 0xc00079a100)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:708 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:706 +0xa1
```

**Comment by maheshwari-mayank** [comment]
Root caused this issue. The sequence of keys is modified when URL received by Rest server.
In GNMI Url is having Name key followed by Type key.
./gnmi_get -xpath /openconfig-acl:acl/acl-sets/acl-set**[name=MyACL1][type=ACL_IPV4]** -target_addr 127.0.0.1:8080 -insecure

But in Rest server, the URL received is having Type key followed by Name key.
translib.go:399] Received Get request for path = /openconfig-acl:acl/acl-sets/acl-set**[type=ACL_IPV4][name=MyACL1]**

**Comment by seiferteric** [comment]
Okay thanks. So will there be a fix? Or we have to pass the keys in that order? The Yang model defines the name key coming first:

```
module: openconfig-acl
  +--rw acl
     +--rw config
     +--ro state
     |  +--ro counter-capability?   identityref
     +--rw acl-sets
     |  +--rw acl-set* [name type]
     |     +--rw name           -> ../config/name
     |     +--rw type           -> ../config/type
     |     +--rw config
     |     |  +--rw name?          string
```

**Comment by seiferteric** [comment]
Also, I think there is more to it. If I reverse the order of the keys, it crashes 100% of the time : `./gnmi_get -xpath /openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL2] -target_addr 127.0.0.1:8080 -insecure`

```
I0806 16:37:21.919900    5268 translib.go:384] Received Get request for path = /openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL2]
I0806 16:37:21.920154    5268 app_interface.go:116] getAppModule called for path =/openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL2]
I0806 16:37:21.920315    5268 app_interface.go:123] found the entry in the map for path =/openconfig-acl:acl
I0806 16:37:21.920662    5268 app_interface.go:154] cast to appInterface worked&{<nil> <nil> <nil> <nil> <nil> map[] map[] false false false}
I0806 16:37:21.921210    5268 acl_app.go:105] initialize:acl:path =/openconfig-acl:acl/acl-sets/acl-set[type=ACL_IPV4][name=MyACL2]
I0806 16:37:21.921477    5268 db.go:310] NewDB: Init indication not requested
I0806 16:37:21.921613    5268 acl_app.go:162] translateGet:acl:path =/openconfig-acl:acl/acl-sets/acl-set{type}{name}
I0806 16:37:21.921807    5268 acl_app.go:305] processCommon--Path Received: /openconfig-acl:acl/acl-sets/acl-set{type}{name}
I0806 16:37:21.921924    5268 acl_app.go:308] processCommon: Target object is a <ptr> of Type: OpenconfigAcl_Acl_AclSets_AclSet
Error handling:  duplicate key {MyACL2 1} for list AclSet
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 13 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.12/src/reflect/value.go:1813 +0x169
github.com/openconfig/ygot/ygot.BuildEmptyTree(0xd90840, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/github.com/openconfig/ygot/ygot/struct_validation_map.go:140 +0xd7
translib.(*AclApp).convertInternalToOCAcl(0xc0005c0640, 0x0, 0x0, 0xc0000b2088, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:614 +0x37a
translib.(*AclApp).processCommonToplevelPath(0xc0005c0640, 0xc0005bb860, 0xc0001b8cc0, 0x1, 0x0, 0x0, 0x2)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:502 +0x16a
translib.(*AclApp).processCommon(0xc0005c0640, 0xc0005bb860, 0x1, 0x2, 0x2)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:420 +0x1b5a
translib.(*AclApp).processGet(0xc0005c0640, 0xc0005bb6e0, 0xc0005bb740, 0xc0005bb7a0, 0xc0005bb800, 0xc0005bb860, 0xc0005bb8c0, 0xc0005bb920, 0x0, 0x0, ...)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/acl_app.go:275 +0x45
translib.Get(0xc00046e370, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/src/translib/translib.go:416 +0x2ea
transl_utils.TranslProcessGet(0xc00046e370, 0x40, 0x0, 0x0, 0x0, 0xb5ac80)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/transl_utils/transl_utils.go:83 +0x4d
sonic_data_client.(*TranslClient).Get(0xc0005b2a00, 0x0, 0x1, 0xc0000b2068, 0xda5fa0, 0xc0005b2a00, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/sonic_data_client/transl_data_client.go:64 +0x123
gnmi_server.(*Server).Get(0xc000189050, 0xd9f880, 0xc0003055f0, 0xc000571e80, 0xc000189050, 0xc0003055f0, 0xc00074aba8)
	/home/eseifert/work/sonic/sonic-buildimage/src/telemetry/src/gnmi_server/server.go:181 +0x417
github.com/openconfig/gnmi/proto/gnmi._GNMI_Get_Handler(0xc06e80, 0xc000189050, 0xd9f880, 0xc0003055f0, 0xc0002db310, 0x0, 0xd9f880, 0xc0003055f0, 0xc0004e18c0, 0x55)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/github.com/openconfig/gnmi/proto/gnmi/gnmi.pb.go:2442 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d2000, 0xda7fe0, 0xc00059be00, 0xc0001aa200, 0xc0001891a0, 0x1538a98, 0x0, 0x0, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:989 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc0000d2000, 0xda7fe0, 0xc00059be00, 0xc0001aa200, 0x0)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:1269 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000590e40, 0xc0000d2000, 0xda7fe0, 0xc00059be00, 0xc0001aa200)
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:708 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/eseifert/work/sonic/sonic-buildimage/src/sonic-mgmt-framework/gopkgs/src/google.golang.org/grpc/server.go:706 +0xa1
```

**Comment by maheshwari-mayank** [comment]
It is fixed. Please check.

**Comment by seiferteric** [comment]
Yes I see that it is fixed now. Thanks.
