### ISSUE TITLE
CLI: show system processes does not work

### ISSUE THREAD

**Issue by mingjunzhang2019** [project-arlo/sonic-mgmt-framework#88]
```
sonic# show system processes
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-sys.py", line 147, in <module>
    run(func, sys.argv[2:])
  File "/usr/sbin/cli/sonic-cli-sys.py", line 114, in run
    if proc['pid'] == int(sys.argv[3]):
ValueError: invalid literal for int() with base 10: 'show'

sonic# show system processes pid 1
-----------------------------------------------------------
Attribute            Value/State
-----------------------------------------------------------
Memory Usage        :59002880
Uptime              :283
Start Time          :1567718580000000000
Name                :/sbin/init
Args                :None
Pid                 :1
Memory Utilization  :0
Cpu Utilization     :0
Cpu Usage System    :272
Cpu Usage User      :646
sonic# show system processes pid 100
command works
```

**Comment by jeffyin-dell** [comment]
@arunsundark what's the latest on this?

**Comment by arunsundark** [comment]
I am testing my changes on a box. I will raise a PR within an hour

**Comment by arunsundark** [comment]
I have raised a pull request. See link https://github.com/project-arlo/sonic-mgmt-framework/pull/110

**Comment by jeffyin-dell** [comment]
Merged
